export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_STARTED = "REGISTER_STARTED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const FORGOT_PASSWORD_STARTED = "FORGOT_PASSWORD_STARTED";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";
export const EMAIL_DOES_NOT_EXIST = "EMAIL_DOES_NOT_EXIST";

export const RESET_PASSWORD_STARTED = "RESET_PASSWORD_STARTED";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const ADD_HIRING_TEMPLATE_STARTED = "ADD_HIRING_TEMPLATE_STARTED";
export const ADD_HIRING_TEMPLATE_SUCCESS = "ADD_HIRING_TEMPLATE_SUCCESS";
export const ADD_HIRING_TEMPLATE_FAILED = "ADD_HIRING_TEMPLATE_FAILED";
export const CLOSE_HIRING_TEMPLATE_MODAL = "CLOSE_HIRING_TEMPLATE_MODAL";
export const OPEN_HIRING_TEMPLATE_MODAL = "OPEN_HIRING_TEMPLATE_MODAL";

export const ADD_HIRING_STAGE_STARTED = "ADD_HIRING_STAGE_STARTED";
export const ADD_HIRING_STAGE_SUCCESS = "ADD_HIRING_STAGE_SUCCESS";
export const ADD_HIRING_STAGE_FAILED = "ADD_HIRING_STAGE_FAILED";
export const CLOSE_HIRING_STAGE_MODAL = "CLOSE_HIRING_STAGE_MODAL";
export const OPEN_HIRING_STAGE_MODAL = "OPEN_HIRING_STAGE_MODAL";
export const GET_HIRING_STAGES_CATEGORIES_SUCCESS = "GET_HIRING_STAGES_CATEGORIES_SUCCESS";
export const GET_HIRING_STAGES_SUCCESS = "GET_HIRING_STAGES_SUCCESS";
export const EDIT_HIRING_STAGE_SUCCESS = "EDIT_HIRING_STAGE_SUCCESS"
export const EDIT_HIRING_STAGE_FAILED = "EDIT_HIRING_STAGE_FAILED"
export const EDIT_HIRING_STAGE_STARTED = "EDIT_HIRING_STAGE_STARTED"

export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

("GET_RETRREIVE_TEMPLATE_CATEGORIES");
export const ADD_RETRREIVE_TEMPLATE_SUCCESS = "ADD_RETRREIVE_TEMPLATE_SUCCESS";
export const ADD_RETRREIVE_TEMPLATE_FAILED = "ADD_RETRREIVE_TEMPLATE_FAILED";
export const ADD_RETRREIVE_TEMPLATE_STARTED = "ADD_RETRREIVE_TEMPLATE_STARTED";

export const ADD_ALL_TEMPLATE_SUCCESS = "ADD_ALL_TEMPLATE_SUCCESS";
export const ADD_ALL_TEMPLATE_FAILED = "ADD_ALL_TEMPLATE_FAILED";
export const ADD_ALL_TEMPLATE_STARTED = "ADD_ALL_TEMPLATE_STARTED";

"GET_ALL_EMAIL_STARTED";
export const ADD_EMAIL_TEMPLATE_SUCCESS = "ADD_EMAIL_TEMPLATE_SUCCESS";
export const ADD_EMAIL_TEMPLATE_FAILED = "ADD_EMAIL_TEMPLATE_FAILED";
export const ADD_EMAIL_TEMPLATE_STARTED = "ADD_EMAIL_TEMPLATE_STARTED";
export const GET_ALL_EMAIL_TEMPLATE_SUCCESS =  "GET_ALL_EMAIL_TEMPLATE_SUCCESS" ;
export const GET_ALL_EMAIL_TEMPLATE_FAILED =  "GET_ALL_EMAIL_TEMPLATE_FAILED" ;
export const GET_ALL_EMAIL_TEMPLATE_STARTED =  "GET_ALL_EMAIL_TEMPLATE_STARTED";
export const GET_RETREIVE_EMAIL_TEMPLATE_SUCCESS = 'GET_RETREIVE_EMAIL_TEMPLATE_SUCCESS';
export const GET_RETREIVE_EMAIL_TEMPLATE_FAILED = 'GET_RETREIVE_EMAIL_TEMPLATE_FAILED';
export const GET_RETREIVE_EMAIL_TEMPLATE_STARTED = 'GET_RETREIVE_EMAIL_TEMPLATE_STARTED';

("Rating Area");
export const ADD_SACLE_RATING_SUCCESS = "ADD_SACLE_RATING_SUCCESS";
export const ADD_SACLE_RATING_FAILED = "ADD_SACLE_RATING_FAILED";
export const ADD_SACLE_RATING_STARTED = "ADD_SACLE_RATING_STARTED";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_ALL_SCALES_STARTED = "GET_ALL_SCALES_STARTED";
export const GET_ALL_SCALES_FAILED = "GET_ALL_SCALES_FAILED";
export const GET_ALL_SCALES_SUCCESS = "GET_ALL_SCALES_SUCCESS";
export const ADD_SCALES_CRITERIA_SUCCESS = "ADD_SCALES_CRITERIA_SUCCESS";
export const ADD_SCALES_CRITERIA_FAILED = "ADD_SCALES_CRITERIA_FAILED";
export const ADD_SCALES_CRITERIA_STARTED = "ADD_SCALES_CRITERIA_STARTED";
export const GET_ALL_SCALES_CRITERIA_SUCCESS =
  "GET_ALL_SCALES_CRITERIA_SUCCESS";
export const GET_ALL_SCALES_CRITERIA_FAILED = "GET_ALL_SCALES_CRITERIA_FAILED";
export const GET_ALL_SCALES_CRITERIA_STARTED = "GET_ALL_SCALES_CRITERIA_STARTED";

export const CLIENT_LOGIN_STARTED = "CLIENT_LOGIN_STARTED";
export const CLIENT_LOGIN_SUCCESS = "CLIENT_LOGIN_SUCCESS";
export const CLIENT_LOGIN_FAILED = "CLIENT_LOGIN_FAILED";
